spring:
  application:
    name: academic_curriculum-service

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    netflix:
      eureka:
        client:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    paths-to-match: /**
    packages-to-scan: microservice.academic_curriculum_service

server:
  port: ${SERVER_PORT}
