CREATE TABLE area (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE subject_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE career (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    title_awarded VARCHAR(255),
    modality VARCHAR(255),
    semester_duration VARCHAR(255),
    total_career_credits INT NOT NULL,
    total_obligatory_credits INT NOT NULL,
    total_elective_credits INT NOT NULL,
    career_director_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE professional_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    area_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (area_id) REFERENCES area(id)
);

CREATE TABLE obligatory_subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    serial_number INT,
    key VARCHAR(255) UNIQUE,
    credits INT NOT NULL,
    area_id BIGINT NOT NULL,
    career_id BIGINT NOT NULL,
    subject_series_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    FOREIGN KEY (area_id) REFERENCES area(id),
    FOREIGN KEY (career_id) REFERENCES career(id),
    FOREIGN KEY (subject_series_id) REFERENCES subject_series(id)
);

CREATE TABLE elective_subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    serial_number INT,
    key VARCHAR(255) UNIQUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    area_id BIGINT NOT NULL,
    career_id BIGINT NOT NULL,
    subject_series_id BIGINT,
    credits INT NOT NULL,
    professional_line_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    FOREIGN KEY (area_id) REFERENCES area(id),
    FOREIGN KEY (career_id) REFERENCES career(id),
    FOREIGN KEY (professional_line_id) REFERENCES professional_line(id)
    FOREIGN KEY (subject_series_id) REFERENCES subject_series(id)
);

CREATE TABLE area_obligatory_subject (
    area_id BIGINT,
    obligatory_subject_id BIGINT,
    PRIMARY KEY (area_id, obligatory_subject_id),
    FOREIGN KEY (area_id) REFERENCES area(id),
    FOREIGN KEY (obligatory_subject_id) REFERENCES obligatory_subject(id)
);


CREATE TABLE area_elective_subject (
    area_id BIGINT,
    elective_subject_id BIGINT,
    PRIMARY KEY (area_id, elective_subject_id),
    FOREIGN KEY (area_id) REFERENCES area(id),
    FOREIGN KEY (elective_subject_id) REFERENCES elective_subject(id)
);
